version: '2'

services:
  web:
    build: .
    environment:
      - PORTUS_MACHINE_FQDN_VALUE=172.17.0.1
      - PORTUS_PRODUCTION_HOST=db
      - PORTUS_PRODUCTION_PASSWORD=portus
      - PORTUS_PRODUCTION_DATABASE="portus_production"

      - PORTUS_PASSWORD="12341234"
      - PORTUS_SECRET_KEY_BASE="b494a25faa8d22e430e843e220e424e10ac84d2ce0e64231f5b636d21251eb6d267adb042ad5884cbff0f3891bcf911bdf8abb3ce719849ccda9a4889249e5c2"
    ports:
      - 3000:3000
    links:
      - db

  db:
    image: library/mariadb:10.0.23
    environment:
      MYSQL_ROOT_PASSWORD: portus
      MYSQL_DATABASE: portus_production
